
#pragma once

#include <sstream>
#include <string>

namespace rda
{
    class fix_db
    {
    public:
        static std::string get()
        {
            static std::stringstream ss;
            if (ss.str().empty())
            {
                ss << R"RAW_DELIM(
{
"fix_version": "FIX.5.0",
"tags": {
"1": "Account",
"2": "AdvId",
"3": "AdvRefID",
"4": "AdvSide",
"5": "AdvTransType",
"6": "AvgPx",
"7": "BeginSeqNo",
"8": "BeginString",
"9": "BodyLength",
"10": "CheckSum",
"11": "ClOrdID",
"12": "Commission",
"13": "CommType",
"14": "CumQty",
"15": "Currency",
"16": "EndSeqNo",
"17": "ExecID",
"18": "ExecInst",
"19": "ExecRefID",
"20": "ExecTransType",
"21": "HandlInst",
"22": "SecurityIDSource",
"23": "IOIID",
"24": "IOIOthSvc (no longer used)",
"25": "IOIQltyInd",
"26": "IOIRefID",
"27": "IOIQty",
"28": "IOITransType",
"29": "LastCapacity",
"30": "LastMkt",
"31": "LastPx",
"32": "LastQty",
"33": "NoLinesOfText",
"34": "MsgSeqNum",
"35": "MsgType",
"36": "NewSeqNo",
"37": "OrderID",
"38": "OrderQty",
"39": "OrdStatus",
"40": "OrdType",
"41": "OrigClOrdID",
"42": "OrigTime",
"43": "PossDupFlag",
"44": "Price",
"45": "RefSeqNum",
"46": "RelatdSym (no longer used)",
"47": "Rule80A(No Longer Used)",
"48": "SecurityID",
"49": "SenderCompID",
"50": "SenderSubID",
"51": "SendingDate (no longer used)",
"52": "SendingTime",
"53": "Quantity",
"54": "Side",
"55": "Symbol",
"56": "TargetCompID",
"57": "TargetSubID",
"58": "Text",
"59": "TimeInForce",
"60": "TransactTime",
"61": "Urgency",
"62": "ValidUntilTime",
"63": "SettlType",
"64": "SettlDate",
"65": "SymbolSfx",
"66": "ListID",
"67": "ListSeqNo",
"68": "TotNoOrders",
"69": "ListExecInst",
"70": "AllocID",
"71": "AllocTransType",
"72": "RefAllocID",
"73": "NoOrders",
"74": "AvgPxPrecision",
"75": "TradeDate",
"76": "ExecBroker",
"77": "PositionEffect",
"78": "NoAllocs",
"79": "AllocAccount",
"80": "AllocQty",
"81": "ProcessCode",
"82": "NoRpts",
"83": "RptSeq",
"84": "CxlQty",
"85": "NoDlvyInst",
"86": "DlvyInst",
"87": "AllocStatus",
"88": "AllocRejCode",
"89": "Signature",
"90": "SecureDataLen",
"91": "SecureData",
"92": "BrokerOfCredit",
"93": "SignatureLength",
"94": "EmailType",
"95": "RawDataLength",
"96": "RawData",
"97": "PossResend",
"98": "EncryptMethod",
"99": "StopPx",
"100": "ExDestination",
"102": "CxlRejReason",
"103": "OrdRejReason",
"104": "IOIQualifier",
"105": "WaveNo",
"106": "Issuer",
"107": "SecurityDesc",
"108": "HeartBtInt",
"109": "ClientID",
"110": "MinQty",
"111": "MaxFloor",
"112": "TestReqID",
"113": "ReportToExch",
"114": "LocateReqd",
"115": "OnBehalfOfCompID",
"116": "OnBehalfOfSubID",
"117": "QuoteID",
"118": "NetMoney",
"119": "SettlCurrAmt",
"120": "SettlCurrency",
"121": "ForexReq",
"122": "OrigSendingTime",
"123": "GapFillFlag",
"124": "NoExecs",
"125": "CxlType",
"126": "ExpireTime",
"127": "DKReason",
"128": "DeliverToCompID",
"129": "DeliverToSubID",
"130": "IOINaturalFlag",
"131": "QuoteReqID",
"132": "BidPx",
"133": "OfferPx",
"134": "BidSize",
"135": "OfferSize",
"136": "NoMiscFees",
"137": "MiscFeeAmt",
"138": "MiscFeeCurr",
"139": "MiscFeeType",
"140": "PrevClosePx",
"141": "ResetSeqNumFlag",
"142": "SenderLocationID",
"143": "TargetLocationID",
"144": "OnBehalfOfLocationID",
"145": "DeliverToLocationID",
"146": "NoRelatedSym",
"147": "Subject",
"148": "Headline",
"149": "URLLink",
"150": "ExecType",
"151": "LeavesQty",
"152": "CashOrderQty",
"153": "AllocAvgPx",
"154": "AllocNetMoney",
"155": "SettlCurrFxRate",
"156": "SettlCurrFxRateCalc",
"157": "NumDaysInterest",
"158": "AccruedInterestRate",
"159": "AccruedInterestAmt",
"160": "SettlInstMode",
"161": "AllocText",
"162": "SettlInstID",
"163": "SettlInstTransType",
"164": "EmailThreadID",
"165": "SettlInstSource",
"166": "SettlLocation",
"167": "SecurityType",
"168": "EffectiveTime",
"169": "StandInstDbType",
"170": "StandInstDbName",
"171": "StandInstDbID",
"172": "SettlDeliveryType",
"173": "SettlDepositoryCode",
"174": "SettlBrkrCode",
"175": "SettlInstCode",
"176": "SecuritySettlAgentName",
"177": "SecuritySettlAgentCode",
"178": "SecuritySettlAgentAcctNum",
"179": "SecuritySettlAgentAcctName",
"180": "SecuritySettlAgentContactName",
"181": "SecuritySettlAgentContactPhone",
"182": "CashSettlAgentName",
"183": "CashSettlAgentCode",
"184": "CashSettlAgentAcctNum",
"185": "CashSettlAgentAcctName",
"186": "CashSettlAgentContactName",
"187": "CashSettlAgentContactPhone",
"188": "BidSpotRate",
"189": "BidForwardPoints",
"190": "OfferSpotRate",
"191": "OfferForwardPoints",
"192": "OrderQty2",
"193": "SettlDate2",
"194": "LastSpotRate",
"195": "LastForwardPoints",
"196": "AllocLinkID",
"197": "AllocLinkType",
"198": "SecondaryOrderID",
"199": "NoIOIQualifiers",
"200": "MaturityMonthYear",
"201": "PutOrCall",
"202": "StrikePrice",
"203": "CoveredOrUncovered",
"204": "CustomerOrFirm",
"205": "MaturityDay",
"206": "OptAttribute",
"207": "SecurityExchange",
"208": "NotifyBrokerOfCredit",
"209": "AllocHandlInst",
"210": "MaxShow",
"211": "PegOffsetValue",
"212": "XmlDataLen",
"213": "XmlData",
"214": "SettlInstRefID",
"215": "NoRoutingIDs",
"216": "RoutingType",
"217": "RoutingID",
"218": "Spread",
"219": "Benchmark",
"220": "BenchmarkCurveCurrency",
"221": "BenchmarkCurveName",
"222": "BenchmarkCurvePoint",
"223": "CouponRate",
"224": "CouponPaymentDate",
"225": "IssueDate",
"226": "RepurchaseTerm",
"227": "RepurchaseRate",
"228": "Factor",
"229": "TradeOriginationDate",
"230": "ExDate",
"231": "ContractMultiplier",
"232": "NoStipulations",
"233": "StipulationType",
"234": "StipulationValue",
"235": "YieldType",
"236": "Yield",
"237": "TotalTakedown",
"238": "Concession",
"239": "RepoCollateralSecurityType",
"240": "RedemptionDate",
"241": "UnderlyingCouponPaymentDate",
"242": "UnderlyingIssueDate",
"243": "UnderlyingRepoCollateralSecurityType",
"244": "UnderlyingRepurchaseTerm",
"245": "UnderlyingRepurchaseRate",
"246": "UnderlyingFactor",
"247": "UnderlyingRedemptionDate",
"248": "LegCouponPaymentDate",
"249": "LegIssueDate",
"250": "LegRepoCollateralSecurityType",
"251": "LegRepurchaseTerm",
"252": "LegRepurchaseRate",
"253": "LegFactor",
"254": "LegRedemptionDate",
"255": "CreditRating",
"256": "UnderlyingCreditRating",
"257": "LegCreditRating",
"258": "TradedFlatSwitch",
"259": "BasisFeatureDate",
"260": "BasisFeaturePrice",
"261": "Reserved/Allocated to the Fixed Income proposal",
"262": "MDReqID",
"263": "SubscriptionRequestType",
"264": "MarketDepth",
"265": "MDUpdateType",
"266": "AggregatedBook",
"267": "NoMDEntryTypes",
"268": "NoMDEntries",
"269": "MDEntryType",
"270": "MDEntryPx",
"271": "MDEntrySize",
"272": "MDEntryDate",
"273": "MDEntryTime",
"274": "TickDirection",
"275": "MDMkt",
"276": "QuoteCondition",
"277": "TradeCondition",
"278": "MDEntryID",
"279": "MDUpdateAction",
"280": "MDEntryRefID",
"281": "MDReqRejReason",
"282": "MDEntryOriginator",
"283": "LocationID",
"284": "DeskID",
"285": "DeleteReason",
"286": "OpenCloseSettlFlag",
"287": "SellerDays",
"288": "MDEntryBuyer",
"289": "MDEntrySeller",
"290": "MDEntryPositionNo",
"291": "FinancialStatus",
"292": "CorporateAction",
"293": "DefBidSize",
"294": "DefOfferSize",
"295": "NoQuoteEntries",
"296": "NoQuoteSets",
"297": "QuoteStatus",
"298": "QuoteCancelType",
"299": "QuoteEntryID",
"300": "QuoteRejectReason",
"301": "QuoteResponseLevel",
"302": "QuoteSetID",
"303": "QuoteRequestType",
"304": "TotNoQuoteEntries",
"305": "UnderlyingSecurityIDSource",
"306": "UnderlyingIssuer",
"307": "UnderlyingSecurityDesc",
"308": "UnderlyingSecurityExchange",
"309": "UnderlyingSecurityID",
"310": "UnderlyingSecurityType",
"311": "UnderlyingSymbol",
"312": "UnderlyingSymbolSfx",
"313": "UnderlyingMaturityMonthYear",
"314": "UnderlyingMaturityDay",
"315": "UnderlyingPutOrCall",
"316": "UnderlyingStrikePrice",
"317": "UnderlyingOptAttribute",
"318": "UnderlyingCurrency",
"319": "RatioQty",
"320": "SecurityReqID",
"321": "SecurityRequestType",
"322": "SecurityResponseID",
"323": "SecurityResponseType",
"324": "SecurityStatusReqID",
"325": "UnsolicitedIndicator",
"326": "SecurityTradingStatus",
"327": "HaltReason",
"328": "InViewOfCommon",
"329": "DueToRelated",
"330": "BuyVolume",
"331": "SellVolume",
"332": "HighPx",
"333": "LowPx",
"334": "Adjustment",
"335": "TradSesReqID",
"336": "TradingSessionID",
"337": "ContraTrader",
"338": "TradSesMethod",
"339": "TradSesMode",
"340": "TradSesStatus",
"341": "TradSesStartTime",
"342": "TradSesOpenTime",
"343": "TradSesPreCloseTime",
"344": "TradSesCloseTime",
"345": "TradSesEndTime",
"346": "NumberOfOrders",
"347": "MessageEncoding",
"348": "EncodedIssuerLen",
"349": "EncodedIssuer",
"350": "EncodedSecurityDescLen",
"351": "EncodedSecurityDesc",
"352": "EncodedListExecInstLen",
"353": "EncodedListExecInst",
"354": "EncodedTextLen",
"355": "EncodedText",
"356": "EncodedSubjectLen",
"357": "EncodedSubject",
"358": "EncodedHeadlineLen",
"359": "EncodedHeadline",
"360": "EncodedAllocTextLen",
"361": "EncodedAllocText",
"362": "EncodedUnderlyingIssuerLen",
"363": "EncodedUnderlyingIssuer",
"364": "EncodedUnderlyingSecurityDescLen",
"365": "EncodedUnderlyingSecurityDesc",
"366": "AllocPrice",
"367": "QuoteSetValidUntilTime",
"368": "QuoteEntryRejectReason",
"369": "LastMsgSeqNumProcessed",
"370": "OnBehalfOfSendingTime",
"371": "RefTagID",
"372": "RefMsgType",
"373": "SessionRejectReason",
"374": "BidRequestTransType",
"375": "ContraBroker",
"376": "ComplianceID",
"377": "SolicitedFlag",
"378": "ExecRestatementReason",
"379": "BusinessRejectRefID",
"380": "BusinessRejectReason",
"381": "GrossTradeAmt",
"382": "NoContraBrokers",
"383": "MaxMessageSize",
"384": "NoMsgTypes",
"385": "MsgDirection",
"386": "NoTradingSessions",
"387": "TotalVolumeTraded",
"388": "DiscretionInst",
"389": "DiscretionOffsetValue",
"390": "BidID",
"391": "ClientBidID",
"392": "ListName",
"393": "TotNoRelatedSym",
"394": "BidType",
"395": "NumTickets",
"396": "SideValue1",
"397": "SideValue2",
"398": "NoBidDescriptors",
"399": "BidDescriptorType",
"400": "BidDescriptor",
"401": "SideValueInd",
"402": "LiquidityPctLow",
"403": "LiquidityPctHigh",
"404": "LiquidityValue",
"405": "EFPTrackingError",
"406": "FairValue",
"407": "OutsideIndexPct",
"408": "ValueOfFutures",
"409": "LiquidityIndType",
"410": "WtAverageLiquidity",
"411": "ExchangeForPhysical",
"412": "OutMainCntryUIndex",
"413": "CrossPercent",
"414": "ProgRptReqs",
"415": "ProgPeriodInterval",
"416": "IncTaxInd",
"417": "NumBidders",
"418": "BidTradeType",
"419": "BasisPxType",
"420": "NoBidComponents",
"421": "Country",
"422": "TotNoStrikes",
"423": "PriceType",
"424": "DayOrderQty",
"425": "DayCumQty",
"426": "DayAvgPx",
"427": "GTBookingInst",
"428": "NoStrikes",
"429": "ListStatusType",
"430": "NetGrossInd",
"431": "ListOrderStatus",
"432": "ExpireDate",
"433": "ListExecInstType",
"434": "CxlRejResponseTo",
"435": "UnderlyingCouponRate",
"436": "UnderlyingContractMultiplier",
"437": "ContraTradeQty",
"438": "ContraTradeTime",
"439": "ClearingFirm",
"440": "ClearingAccount",
"441": "LiquidityNumSecurities",
"442": "MultiLegReportingType",
"443": "StrikeTime",
"444": "ListStatusText",
"445": "EncodedListStatusTextLen",
"446": "EncodedListStatusText",
"447": "PartyIDSource",
"448": "PartyID",
"449": "TotalVolumeTradedDate",
"450": "TotalVolumeTraded Time",
"451": "NetChgPrevDay",
"452": "PartyRole",
"453": "NoPartyIDs",
"454": "NoSecurityAltID",
"455": "SecurityAltID",
"456": "SecurityAltIDSource",
"457": "NoUnderlyingSecurityAltID",
"458": "UnderlyingSecurityAltID",
"459": "UnderlyingSecurityAltIDSource",
"460": "Product",
"461": "CFICode",
"462": "UnderlyingProduct",
"463": "UnderlyingCFICode",
"464": "TestMessageIndicator",
"465": "QuantityType",
"466": "BookingRefID",
"467": "IndividualAllocID",
"468": "RoundingDirection",
"469": "RoundingModulus",
"470": "CountryOfIssue",
"471": "StateOrProvinceOfIssue",
"472": "LocaleOfIssue",
"473": "NoRegistDtls",
"474": "MailingDtls",
"475": "InvestorCountryOfResidence",
"476": "PaymentRef",
"477": "DistribPaymentMethod",
"478": "CashDistribCurr",
"479": "CommCurrency",
"480": "CancellationRights",
"481": "MoneyLaunderingStatus",
"482": "MailingInst",
"483": "TransBkdTime",
"484": "ExecPriceType",
"485": "ExecPriceAdjustment",
"486": "DateOfBirth",
"487": "TradeReportTransType",
"488": "CardHolderName",
"489": "CardNumber",
"490": "CardExpDate",
"491": "CardIssNum",
"492": "PaymentMethod",
"493": "RegistAcctType",
"494": "Designation",
"495": "TaxAdvantageType",
"496": "RegistRejReasonText",
"497": "FundRenewWaiv",
                )RAW_DELIM";
                ss << R"RAW_DELIM(
"498": "CashDistribAgentName",
"499": "CashDistribAgentCode",
"500": "CashDistribAgentAcctNumber",
"501": "CashDistribPayRef",
"502": "CashDistribAgentAcctName",
"503": "CardStartDate",
"504": "PaymentDate",
"505": "PaymentRemitterID",
"506": "RegistStatus",
"507": "RegistRejReasonCode",
"508": "RegistRefID",
"509": "RegistDtls",
"510": "NoDistribInsts",
"511": "RegistEmail",
"512": "DistribPercentage",
"513": "RegistID",
"514": "RegistTransType",
"515": "ExecValuationPoint",
"516": "OrderPercent",
"517": "OwnershipType",
"518": "NoContAmts",
"519": "ContAmtType",
"520": "ContAmtValue",
"521": "ContAmtCurr",
"522": "OwnerType",
"523": "PartySubID",
"524": "NestedPartyID",
"525": "NestedPartyIDSource",
"526": "SecondaryClOrdID",
"527": "SecondaryExecID",
"528": "OrderCapacity",
"529": "OrderRestrictions",
"530": "MassCancelRequestType",
"531": "MassCancelResponse",
"532": "MassCancelRejectReason",
"533": "TotalAffectedOrders",
"534": "NoAffectedOrders",
"535": "AffectedOrderID",
"536": "AffectedSecondaryOrderID",
"537": "QuoteType",
"538": "NestedPartyRole",
"539": "NoNestedPartyIDs",
"540": "TotalAccruedInterestAmt",
"541": "MaturityDate",
"542": "UnderlyingMaturityDate",
"543": "InstrRegistry",
"544": "CashMargin",
"545": "NestedPartySubID",
"546": "Scope",
"547": "MDImplicitDelete",
"548": "CrossID",
"549": "CrossType",
"550": "CrossPrioritization",
"551": "OrigCrossID",
"552": "NoSides",
"553": "Username",
"554": "Password",
"555": "NoLegs",
"556": "LegCurrency",
"557": "TotNoSecurityTypes",
"558": "NoSecurityTypes",
"559": "SecurityListRequestType",
"560": "SecurityRequestResult",
"561": "RoundLot",
"562": "MinTradeVol",
"563": "MultiLegRptTypeReq",
"564": "LegPositionEffect",
"565": "LegCoveredOrUncovered",
"566": "LegPrice",
"567": "TradSesStatusRejReason",
"568": "TradeRequestID",
"569": "TradeRequestType",
"570": "PreviouslyReported",
"571": "TradeReportID",
"572": "TradeReportRefID",
"573": "MatchStatus",
"574": "MatchType",
"575": "OddLot",
"576": "NoClearingInstructions",
"577": "ClearingInstruction",
"578": "TradeInputSource",
"579": "TradeInputDevice",
"580": "NoDates",
"581": "AccountType",
"582": "CustOrderCapacity",
"583": "ClOrdLinkID",
"584": "MassStatusReqID",
"585": "MassStatusReqType",
"586": "OrigOrdModTime",
"587": "LegSettlType",
"588": "LegSettlDate",
"589": "DayBookingInst",
"590": "BookingUnit",
"591": "PreallocMethod",
"592": "UnderlyingCountryOfIssue",
"593": "UnderlyingStateOrProvinceOfIssue",
"594": "UnderlyingLocaleOfIssue",
"595": "UnderlyingInstrRegistry",
"596": "LegCountryOfIssue",
"597": "LegStateOrProvinceOfIssue",
"598": "LegLocaleOfIssue",
"599": "LegInstrRegistry",
"600": "LegSymbol",
"601": "LegSymbolSfx",
"602": "LegSecurityID",
"603": "LegSecurityIDSource",
"604": "NoLegSecurityAltID",
"605": "LegSecurityAltID",
"606": "LegSecurityAltIDSource",
"607": "LegProduct",
"608": "LegCFICode",
"609": "LegSecurityType",
"610": "LegMaturityMonthYear",
"611": "LegMaturityDate",
"612": "LegStrikePrice",
"613": "LegOptAttribute",
"614": "LegContractMultiplier",
"615": "LegCouponRate",
"616": "LegSecurityExchange",
"617": "LegIssuer",
"618": "EncodedLegIssuerLen",
"619": "EncodedLegIssuer",
"620": "LegSecurityDesc",
"621": "EncodedLegSecurityDescLen",
"622": "EncodedLegSecurityDesc",
"623": "LegRatioQty",
"624": "LegSide",
"625": "TradingSessionSubID",
"626": "AllocType",
"627": "NoHops",
"628": "HopCompID",
"629": "HopSendingTime",
"630": "HopRefID",
"631": "MidPx",
"632": "BidYield",
"633": "MidYield",
"634": "OfferYield",
"635": "ClearingFeeIndicator",
"636": "WorkingIndicator",
"637": "LegLastPx",
"638": "PriorityIndicator",
"639": "PriceImprovement",
"640": "Price2",
"641": "LastForwardPoints2",
"642": "BidForwardPoints2",
"643": "OfferForwardPoints2",
"644": "RFQReqID",
"645": "MktBidPx",
"646": "MktOfferPx",
"647": "MinBidSize",
"648": "MinOfferSize",
"649": "QuoteStatusReqID",
"650": "LegalConfirm",
"651": "UnderlyingLastPx",
"652": "UnderlyingLastQty",
"653": "SecDefStatus",
"654": "LegRefID",
"655": "ContraLegRefID",
"656": "SettlCurrBidFxRate",
"657": "SettlCurrOfferFxRate",
"658": "QuoteRequestRejectReason",
"659": "SideComplianceID",
"660": "AcctIDSource",
"661": "AllocAcctIDSource",
"662": "BenchmarkPrice",
"663": "BenchmarkPriceType",
"664": "ConfirmID",
"665": "ConfirmStatus",
"666": "ConfirmTransType",
"667": "ContractSettlMonth",
"668": "DeliveryForm",
"669": "LastParPx",
"670": "NoLegAllocs",
"671": "LegAllocAccount",
"672": "LegIndividualAllocID",
"673": "LegAllocQty",
"674": "LegAllocAcctIDSource",
"675": "LegSettlCurrency",
"676": "LegBenchmarkCurveCurrency",
"677": "LegBenchmarkCurveName",
"678": "LegBenchmarkCurvePoint",
"679": "LegBenchmarkPrice",
"680": "LegBenchmarkPriceType",
"681": "LegBidPx",
"682": "LegIOIQty",
"683": "NoLegStipulations",
"684": "LegOfferPx",
"685": "LegOrderQty",
"686": "LegPriceType",
"687": "LegQty",
"688": "LegStipulationType",
"689": "LegStipulationValue",
"690": "LegSwapType",
"691": "Pool",
"692": "QuotePriceType",
"693": "QuoteRespID",
"694": "QuoteRespType",
"695": "QuoteQualifier",
"696": "YieldRedemptionDate",
"697": "YieldRedemptionPrice",
"698": "YieldRedemptionPriceType",
"699": "BenchmarkSecurityID",
"700": "ReversalIndicator",
"701": "YieldCalcDate",
"702": "NoPositions",
"703": "PosType",
"704": "LongQty",
"705": "ShortQty",
"706": "PosQtyStatus",
"707": "PosAmtType",
"708": "PosAmt",
"709": "PosTransType",
"710": "PosReqID",
"711": "NoUnderlyings",
"712": "PosMaintAction",
"713": "OrigPosReqRefID",
"714": "PosMaintRptRefID",
"715": "ClearingBusinessDate",
"716": "SettlSessID",
"717": "SettlSessSubID",
"718": "AdjustmentType",
"719": "ContraryInstructionIndicator",
"720": "PriorSpreadIndicator",
"721": "PosMaintRptID",
"722": "PosMaintStatus",
"723": "PosMaintResult",
"724": "PosReqType",
"725": "ResponseTransportType",
"726": "ResponseDestination",
"727": "TotalNumPosReports",
"728": "PosReqResult",
"729": "PosReqStatus",
"730": "SettlPrice",
"731": "SettlPriceType",
"732": "UnderlyingSettlPrice",
"733": "UnderlyingSettlPriceType",
"734": "PriorSettlPrice",
"735": "NoQuoteQualifiers",
"736": "AllocSettlCurrency",
"737": "AllocSettlCurrAmt",
"738": "InterestAtMaturity",
"739": "LegDatedDate",
"740": "LegPool",
"741": "AllocInterestAtMaturity",
"742": "AllocAccruedInterestAmt",
"743": "DeliveryDate",
"744": "AssignmentMethod",
"745": "AssignmentUnit",
"746": "OpenInterest",
"747": "ExerciseMethod",
"748": "TotNumTradeReports",
"749": "TradeRequestResult",
"750": "TradeRequestStatus",
"751": "TradeReportRejectReason",
"752": "SideMultiLegReportingType",
"753": "NoPosAmt",
"754": "AutoAcceptIndicator",
"755": "AllocReportID",
"756": "NoNested2PartyIDs",
"757": "Nested2PartyID",
"758": "Nested2PartyIDSource",
"759": "Nested2PartyRole",
"760": "Nested2PartySubID",
"761": "BenchmarkSecurityIDSource",
"762": "SecuritySubType",
"763": "UnderlyingSecuritySubType",
"764": "LegSecuritySubType",
"765": "AllowableOneSidednessPct",
"766": "AllowableOneSidednessValue",
"767": "AllowableOneSidednessCurr",
"768": "NoTrdRegTimestamps",
"769": "TrdRegTimestamp",
"770": "TrdRegTimestampType",
"771": "TrdRegTimestampOrigin",
"772": "ConfirmRefID",
"773": "ConfirmType",
"774": "ConfirmRejReason",
"775": "BookingType",
"776": "IndividualAllocRejCode",
"777": "SettlInstMsgID",
"778": "NoSettlInst",
"779": "LastUpdateTime",
"780": "AllocSettlInstType",
"781": "NoSettlPartyIDs",
"782": "SettlPartyID",
"783": "SettlPartyIDSource",
"784": "SettlPartyRole",
"785": "SettlPartySubID",
"786": "SettlPartySubIDType",
"787": "DlvyInstType",
"788": "TerminationType",
"789": "NextExpectedMsgSeqNum",
"790": "OrdStatusReqID",
"791": "SettlInstReqID",
"792": "SettlInstReqRejCode",
"793": "SecondaryAllocID",
"794": "AllocReportType",
"795": "AllocReportRefID",
"796": "AllocCancReplaceReason",
"797": "CopyMsgIndicator",
"798": "AllocAccountType",
"799": "OrderAvgPx",
"800": "OrderBookingQty",
"801": "NoSettlPartySubIDs",
"802": "NoPartySubIDs",
"803": "PartySubIDType",
"804": "NoNestedPartySubIDs",
"805": "NestedPartySubIDType",
"806": "NoNested2PartySubIDs",
"807": "Nested2PartySubIDType",
"808": "AllocIntermedReqType",
"809": "(Not Defined)",
"810": "UnderlyingPx",
"811": "PriceDelta",
"812": "ApplQueueMax",
"813": "ApplQueueDepth",
"814": "ApplQueueResolution",
"815": "ApplQueueAction",
"816": "NoAltMDSource",
"817": "AltMDSourceID",
"818": "SecondaryTradeReportID",
"819": "AvgPxIndicator",
"820": "TradeLinkID",
"821": "OrderInputDevice",
"822": "UnderlyingTradingSessionID",
"823": "UnderlyingTradingSessionSubID",
"824": "TradeLegRefID",
"825": "ExchangeRule",
"826": "TradeAllocIndicator",
"827": "ExpirationCycle",
"828": "TrdType",
"829": "TrdSubType",
"830": "TransferReason",
"831": "AsgnReqID",
"832": "TotNumAssignmentReports",
"833": "AsgnRptID",
"834": "ThresholdAmount",
"835": "PegMoveType",
"836": "PegOffsetType",
"837": "PegLimitType",
"838": "PegRoundDirection",
"839": "PeggedPrice",
"840": "PegScope",
"841": "DiscretionMoveType",
"842": "DiscretionOffsetType",
"843": "DiscretionLimitType",
"844": "DiscretionRoundDirection",
"845": "DiscretionPrice",
"846": "DiscretionScope",
"847": "TargetStrategy",
"848": "TargetStrategyParameters",
"849": "ParticipationRate",
"850": "TargetStrategyPerformance",
"851": "LastLiquidityInd",
"852": "PublishTrdIndicator",
"853": "ShortSaleReason",
"854": "QtyType",
"855": "SecondaryTrdType",
"856": "TradeReportType",
"857": "AllocNoOrdersType",
"858": "SharedCommission",
"859": "ConfirmReqID",
"860": "AvgParPx",
"861": "ReportedPx",
"862": "NoCapacities",
"863": "OrderCapacityQty",
"864": "NoEvents",
"865": "EventType",
"866": "EventDate",
"867": "EventPx",
"868": "EventText",
"869": "PctAtRisk",
"870": "NoInstrAttrib",
"871": "InstrAttribType",
"872": "InstrAttribValue",
"873": "DatedDate",
"874": "InterestAccrualDate",
"875": "CPProgram",
"876": "CPRegType",
"877": "UnderlyingCPProgram",
"878": "UnderlyingCPRegType",
"879": "UnderlyingQty",
"880": "TrdMatchID",
"881": "SecondaryTradeReportRefID",
"882": "UnderlyingDirtyPrice",
"883": "UnderlyingEndPrice",
"884": "UnderlyingStartValue",
"885": "UnderlyingCurrentValue",
"886": "UnderlyingEndValue",
"887": "NoUnderlyingStips",
"888": "UnderlyingStipType",
"889": "UnderlyingStipValue",
"890": "MaturityNetMoney",
"891": "MiscFeeBasis",
"892": "TotNoAllocs",
"893": "LastFragment",
"894": "CollReqID",
"895": "CollAsgnReason",
"896": "CollInquiryQualifier",
"897": "NoTrades",
"898": "MarginRatio",
"899": "MarginExcess",
"900": "TotalNetValue",
"901": "CashOutstanding",
"902": "CollAsgnID",
"903": "CollAsgnTransType",
"904": "CollRespID",
"905": "CollAsgnRespType",
"906": "CollAsgnRejectReason",
"907": "CollAsgnRefID",
"908": "CollRptID",
"909": "CollInquiryID",
"910": "CollStatus",
"911": "TotNumReports",
"912": "LastRptRequested",
"913": "AgreementDesc",
"914": "AgreementID",
"915": "AgreementDate",
"916": "StartDate",
"917": "EndDate",
"918": "AgreementCurrency",
"919": "DeliveryType",
"920": "EndAccruedInterestAmt",
"921": "StartCash",
"922": "EndCash",
"923": "UserRequestID",
"924": "UserRequestType",
"925": "NewPassword",
"926": "UserStatus",
"927": "UserStatusText",
"928": "StatusValue",
"929": "StatusText",
"930": "RefCompID",
"931": "RefSubID",
"932": "NetworkResponseID",
"933": "NetworkRequestID",
"934": "LastNetworkResponseID",
"935": "NetworkRequestType",
"936": "NoCompIDs",
"937": "NetworkStatusResponseType",
"938": "NoCollInquiryQualifier",
"939": "TrdRptStatus",
"940": "AffirmStatus",
"941": "UnderlyingStrikeCurrency",
"942": "LegStrikeCurrency",
"943": "TimeBracket",
"944": "CollAction",
"945": "CollInquiryStatus",
"946": "CollInquiryResult",
"947": "StrikeCurrency",
"948": "NoNested3PartyIDs",
"949": "Nested3PartyID",
"950": "Nested3PartyIDSource",
"951": "Nested3PartyRole",
"952": "NoNested3PartySubIDs",
"953": "Nested3PartySubID",
"954": "Nested3PartySubIDType",
"955": "LegContractSettlMonth",
"956": "LegInterestAccrualDate",
"957": "NoStrategyParameters",
"958": "StrategyParameterName",
"959": "StrategyParameterType",
"960": "StrategyParameterValue",
"961": "HostCrossID",
"962": "SideTimeInForce",
"963": "MDReportID",
"964": "SecurityReportID",
"965": "SecurityStatus",
"966": "SettleOnOpenFlag",
"967": "StrikeMultiplier",
"968": "StrikeValue",
"969": "MinPriceIncrement",
"970": "PositionLimit",
"971": "NTPositionLimit",
"972": "UnderlyingAllocationPercent",
"973": "UnderlyingCashAmount",
"974": "UnderlyingCashType",
"975": "UnderlyingSettlementType",
"976": "QuantityDate",
"977": "ContIntRptID",
"978": "LateIndicator",
"979": "InputSource",
"980": "SecurityUpdateAction",
"981": "NoExpiration",
"982": "ExpType",
"983": "ExpQty",
"984": "NoUnderlyingAmounts",
"985": "UnderlyingPayAmount",
"986": "UnderlyingCollectAmount",
"987": "UnderlyingSettlementDate",
"988": "UnderlyingSettlementStatus",
"989": "SecondaryIndividualAllocID",
"990": "LegReportID",
"991": "RndPx",
"992": "IndividualAllocType",
"993": "AllocCustomerCapacity",
"994": "TierCode",
"996": "UnitofMeasure",
"997": "TimeUnit",
"998": "UnderlyingUnitofMeasure",
                )RAW_DELIM";
                ss << R"RAW_DELIM(
"999": "LegUnitofMeasure",
"1000": "UnderlyingTimeUnit",
"1001": "LegTimeUnit",
"1002": "AllocMethod",
"1003": "TradeID",
"1005": "SideTradeReportID",
"1006": "SideFillStationCd",
"1007": "SideReasonCd",
"1008": "SideTrdSubTyp",
"1009": "SideQty",
"1011": "MessageEventSource",
"1012": "SideTrdRegTimestamp",
"1013": "SideTrdRegTimestampType",
"1014": "SideTrdRegTimestampSrc",
"1015": "AsOfIndicator",
"1016": "NoSideTrdRegTS",
"1017": "LegOptionRatio",
"1018": "NoInstrumentParties",
"1019": "InstrumentPartyID",
"1020": "TradeVolume",
"1021": "MDBookType",
"1022": "MDFeedType",
"1023": "MDPriceLevel",
"1024": "MDOriginType",
"1025": "FirstPx",
"1026": "MDEntrySpotRate",
"1027": "MDEntryForwardPoints",
"1028": "ManualOrderIndicator",
"1029": "CustDirectedOrder",
"1030": "ReceivedDeptID",
"1031": "CustOrderHandlingInst",
"1032": "OrderHandlingInstSource",
"1033": "DeskType",
"1034": "DeskTypeSource",
"1035": "DeskOrderHandlingInst",
"1036": "ExecAckStatus",
"1037": "UnderlyingDeliveryAmount",
"1038": "UnderlyingCapValue",
"1039": "UnderlyingSettlMethod",
"1040": "SecondaryTradeID",
"1041": "FirmTradeID",
"1042": "SecondaryFirmTradeID",
"1043": "CollApplType",
"1044": "UnderlyingAdjustedQuantity",
"1045": "UnderlyingFXRate",
"1046": "UnderlyingFXRateCalc",
"1047": "AllocPositionEffect",
"1048": "DealingCapacity",
"1049": "InstrmtAssignmentMethod",
"1050": "InstrumentPartyIDSource",
"1051": "InstrumentPartyRole",
"1052": "NoInstrumentPartySubIDs",
"1053": "InstrumentPartySubID",
"1054": "InstrumentPartySubIDType",
"1055": "PositionCurrency",
"1056": "CalculatedCcyLastQty",
"1057": "AggressorIndicator",
"1058": "NoUndlyInstrumentParties",
"1059": "UndlyInstrumentPartyID",
"1060": "UndlyInstrumentPartyIDSource",
"1061": "UndlyInstrumentPartyRole",
"1062": "NoUndlyInstrumentPartySubIDs",
"1063": "UndlyInstrumentPartySubID",
"1064": "UndlyInstrumentPartySubIDType",
"1065": "BidSwapPoints",
"1066": "OfferSwapPoints",
"1067": "LegBidForwardPoints",
"1068": "LegOfferForwardPoints",
"1069": "SwapPoints",
"1070": "MDQuoteType",
"1071": "LastSwapPoints",
"1072": "SideGrossTradeAmt",
"1073": "LegLastForwardPoints",
"1074": "LegCalculatedCcyLastQty",
"1075": "LegGrossTradeAmt",
"1079": "MaturityTime",
"1080": "RefOrderID",
"1081": "RefOrderIDSource",
"1082": "SecondaryDisplayQty",
"1083": "DisplayWhen",
"1084": "DisplayMethod",
"1085": "DisplayLowQty",
"1086": "DisplayHighQty",
"1087": "DisplayMinIncr",
"1088": "RefreshQty",
"1089": "MatchIncrement",
"1090": "MaxPriceLevels",
"1091": "PreTradeAnonymity",
"1092": "PriceProtectionScope",
"1093": "LotType",
"1094": "PegPriceType",
"1095": "PeggedRefPrice",
"1096": "PegSecurityIDSource",
"1097": "PegSecurityID",
"1098": "PegSymbol",
"1099": "PegSecurityDesc",
"1100": "TriggerType",
"1101": "TriggerAction",
"1102": "TriggerPrice",
"1103": "TriggerSymbol",
"1104": "TriggerSecurityID",
"1105": "TriggerSecurityIDSource",
"1106": "TriggerSecurityDesc",
"1107": "TriggerPriceType",
"1108": "TriggerPriceTypeScope",
"1109": "TriggerPriceDirection",
"1110": "TriggerNewPrice",
"1111": "TriggerOrderType",
"1112": "TriggerNewQty",
"1113": "TriggerTradingSessionID",
"1114": "TriggerTradingSessionSubID",
"1115": "OrderCategory",
"1116": "NoRootPartyIDs",
"1117": "RootPartyID",
"1118": "RootPartyIDSource",
"1119": "RootPartyRole",
"1120": "NoRootPartySubIDs",
"1121": "RootPartySubID",
"1122": "RootPartySubIDType",
"1123": "TradeHandlingInstr",
"1124": "OrigTradeHandlingInstr",
"1125": "OrigTradeDate",
"1126": "OrigTradeID",
"1127": "OrigSecondaryTradeID",
"1128": "ApplVerID",
"1129": "CstmApplVerID",
"1130": "RefApplVerID",
"1131": "RefCstmApplVerID",
"1132": "TZTransactTime",
"1133": "ExDestinationIDSource",
"1134": "ReportedPxDiff",
"1135": "RptSys",
"1136": "AllocClearingFeeIndicator",
"1137": "DefaultApplVerID",
"1138": "DisplayQty",
"1139": "ExchangeSpecialInstructions"
},
"fields": {
"4": {
"B": "Buy",
"S": "Sell",
"T": "Trade",
"X": "Cross"
},
"5": {
"C": "Cancel",
"N": "New",
"R": "Replace"
},
"13": {
"1": "Per Unit (implying shares, par, currency, etc.)",
"2": "Percent",
"3": "Absolute (total monetary amount)",
"4": "Percentage waived - cash discount (for CIV buy orders)",
"5": "Percentage waived -= enhanced units (for CIV buy orders)",
"6": "Points per bond or contract (supply ContractMultiplier (231) in the component block if the object security is denominated in a size other than the industry default - 1000 par for bonds)"
},
"18": {
"0": "Stay on offer side",
"1": "Not held",
"2": "Work",
"3": "Go along",
"4": "Over the day",
"5": "Held",
"6": "Participate don't initiate",
"7": "Strict scale",
"8": "Try to scale",
"9": "Stay on bid side",
"A": "No cross (cross is forbidden)",
"B": "OK to cross",
"C": "Call first",
"D": "Percent of volume (indicates that the sender does not want to be all of the volume on the floor vs. a specific percentage)",
"E": "Do not increase - DNI",
"F": "Do not reduce - DNR",
"G": "All or none - AON",
"H": "Reinstate on System Failue (mutually exclusive with Q)",
"I": "Institutions only",
"J": "Reinstate on Trading Halt (mutually exclusive with K)",
"K": "Cancel on Trading Halt (mutually exclusive with J)",
"L": "Last peg (last sale)",
"M": "Mid-price peg (midprice of inside quote)",
"N": "Non-negotiable",
"O": "Opening peg",
"P": "Market peg",
"Q": "Cancel on system failure (mutually exclusive with H)",
"R": "Primary peg (primary market - buy at bid/sell at offer)",
"S": "Suspend",
"T": "Fixed Peg to Local best bid or offer at time of order",
"U": "Customer Display Instruction (Rule 11Ac1-1/4)",
"V": "Netting (for Forex)",
"W": "Peg to VWAP",
"X": "Trade Along",
"Y": "Try To Stop",
"Z": "Cancel if not best",
"a": "Trailing Stop Peg",
"b": "Strict Limit (No price improvement)",
"c": "Ignore Price Validity Checks",
"d": "Peg to Limit Price",
"e": "Work to Target Strategy",
"f": "Intermarket Sweep",
"g": "External Routing Allowed",
"h": "External Routing Not Allowed",
"i": "Imbalance Only",
"j": "Single execution requested for block trade",
"k": "Best Execution"
},
"20": {
"0": "New",
"1": "Cancel",
"2": "Correct",
"3": "Status"
},
"21": {
"1": "Automated execution order, private, no Broker intervention",
"2": "Automated execution order, public, Broker intervention OK",
"3": "Manual order, best execution"
},
"22": {
"1": "CUSIP",
"2": "SEDOL",
"3": "QUIK",
"4": "ISIN number",
"5": "RIC code",
"6": "ISO Currency Code",
"7": "ISO Country Code",
"8": "Exchange Symbol",
"9": "Consolidated Tape Association (CTA) Symbol (SIAC CTS/CQS line format)",
"A": "Bloomberg Symbol",
"B": "Wertpapier",
"C": "Dutch",
"D": "Valoren",
"E": "Sicovam",
"F": "Belgian",
"G": "'Common' (Clearstream and Euroclear)'",
"H": "Clearing House / Clearing Organization",
"I": "ISDA/FpML Product Specification (XML in EncodedSecurityDesc)",
"J": "Option Price Reporting Authority",
"K": "ISDA/FpML Product URL (URL in SecurityID)",
"L": "Letter of Credit"
},
"25": {
"H": "High",
"L": "Low",
"M": "Medium"
},
"27": {
"0": "1000000000",
"L": "Large",
"M": "Medium",
"S": "Small",
"U": "Undisclosed Quantity"
},
"28": {
"C": "Cancel",
"N": "New",
"R": "Replace"
},
"29": {
"1": "Agent",
"2": "Cross as agent",
"3": "Cross as principal",
"4": "Principal"
},
"35": {
"0": "Heartbeat",
"1": "Test Request",
"2": "Resend Request",
"3": "Reject",
"4": "Sequence Reset",
"5": "Logout",
"6": "Indication of Interest",
"7": "Advertisement",
"8": "Execution Report",
"9": "Order Cancel Reject",
"A": "Logon",
"AA": "Derivative Security List",
"AB": "New Order - Multileg",
"AC": "Multileg Order Cancel/Replace (a.k.a. Multileg Order Modification Request)",
"AD": "Trade Capture Report Request",
"AE": "Trade Capture Report",
"AF": "Order Mass Status Request",
"AG": "Quote Request Reject",
"AH": "RFQ Request",
"AI": "Quote Status Report",
"AJ": "Quote Response",
"AK": "Confirmation",
"AL": "Position Maintenance Request",
"AM": "Position Maintenance Report",
"AN": "Request For Positions",
"AO": "Request For Positions Ack",
"AP": "Position Report",
"AQ": "Trade Capture Report Request Ack",
"AR": "Trade Capture Report Ack",
"AS": "Allocation Report (a.k.a. Allocation Claim)",
"AT": "Allocation Report Ack (a.k.a. Allocation Claim Ack)",
"AU": "Confirmation Ack (a.k.a. Affirmation)",
"AV": "Settlement Instruction Request",
"AW": "Assignment Report",
"AX": "Collateral Request",
"AY": "Collateral Assignment",
"AZ": "Collateral Response",
"B": "News",
"BA": "Collateral Report",
"BB": "Collateral Inquiry",
"BC": "Network Counterparty System Status Request",
"BD": "Network Counterparty System Status Response",
"BE": "User Request",
"BF": "User Response",
"BG": "Collateral Inquiry Ack",
"BH": "Confirmation Request",
"BI": "Trading Session List Request",
"BJ": "Trading Session List",
"BK": "Security List Update Report",
"BL": "Adjusted Position Report",
"BM": "Allocation Instruction Alert",
"BN": "Execution Acknowledgement",
"BO": "Contrary Intention Report",
"BP": "Security Definition Update Report",
"C": "Email",
"D": "New Order - Single",
"E": "New Order - List",
"F": "Order Cancel Request",
"G": "Order Cancel/Replace Request (a.k.a. Order Modification Request)",
"H": "Order Status Request",
"J": "Allocation Instruction",
"K": "List Cancel Request",
"L": "List Execute",
"M": "List Status Request",
"N": "List Status",
"P": "Allocation Instruction Ack",
"Q": "Don't Know Trade (DK)",
"R": "Quote Request",
"S": "Quote",
"T": "Settlement Instructions",
"V": "Market Data Request",
"W": "Market Data - Snapshot/Full Refresh",
"X": "Market Data - Incremental Refresh",
"Y": "Market Data Request Reject",
"Z": "Quote Cancel",
"a": "Quote Status Request",
"b": "Mass Quote Acknowledgement",
"c": "Security Definition Request",
"d": "Security Definition",
"e": "Security Status Request",
"f": "Security Status",
"g": "Trading Session Status Request",
"h": "Trading Session Status",
"i": "Mass Quote",
"j": "Business Message Reject",
"k": "Bid Request",
"l": "Bid Response (lowercase L)",
"m": "List Strike Price",
"n": "XML message (e.g. non FIX Msg Type)",
"o": "Registration Instructions",
"p": "Registration Instructions Response",
"q": "Order Mass Cancel Request",
"r": "Order Mass Cancel Report",
"s": "New Order - Cross",
"t": "Cross Order Cancel/Replace Request (a.k.a. Cross Order Modification Request)",
"u": "Cross Order Cancel Request",
"v": "Security Type Request",
"w": "Security Types",
"x": "Security List Request",
"y": "Security List",
"z": "Derivative Security List Request"
},
"39": {
"0": "New",
"1": "Partially filled",
"2": "Filled",
"3": "Done for day",
"4": "Canceled",
"5": "Replaced (No longer used)",
"6": "Pending Cancel (i.e. result of Order Cancel Request <F>)",
"7": "Stopped",
"8": "Rejected",
"9": "Suspended",
"A": "Pending New",
"B": "Calculated",
"C": "Expired",
"D": "Accepted for Bidding",
"E": "Pending Replace (i.e. result of Order Cancel/Replace Request <G>)"
},
"40": {
"1": "Market",
"2": "Limit",
"3": "Stop / Stop Loss",
"4": "Stop Limit",
"5": "Market On Close (No longer used)",
"6": "With Or Without",
"7": "Limit Or Better",
"8": "Limit With Or Without",
"9": "On Basis",
"A": "On Close (No longer used)",
"B": "Limit On Close (No longer used)",
"C": "Forex Market (No longer used)",
"D": "Previously Quoted",
"E": "Previously Indicated",
"F": "Forex Limit (No longer used)",
"G": "Forex Swap",
"H": "Forex Previously Quoted (No longer used)",
"I": "Funari (Limit day order with unexecuted portion handles as Market On Close. E.g. Japan)",
"J": "Market If Touched (MIT)",
"K": "Market With Left Over as Limit (market order with unexecuted quantity becoming limit order at last price)",
"L": "Previous Fund Valuation Point (Historic pricing; for CIV)",
"M": "Next Fund Valuation Point (Forward pricing; for CIV)",
"P": "Pegged",
"Q": "Counter-Order Selection"
},
"43": {
"N": "Original transmission",
"Y": "Possible duplicate"
},
"47": {
"A": "Agency single order",
"B": "Short exempt transaction (refer to A type)",
"C": "Program order, non-index arb, for Member firm/org",
"D": "Program order, index arb, for Member firm/org",
"E": "Short Exempt Transaction for Principal (was incorrectly identified in the FIX spec as 'Registered Equity Market Maker trades')",
"F": "Short exempt transaction (refer to W type)",
"H": "Short exempt transaction (refer to I type)",
"I": "Individual Investor, single order",
"J": "Program Order, index arb, for individual customer",
"K": "Program Order, non-index arb, for individual customer",
"L": "Short exempt transaction for member competing market-maker affliated with the firm clearing the trade (refer to P and O types)",
"M": "Program Order, index arb, for other member",
"N": "Program Order, non-index arb, for other member",
"O": "Proprietary transactions for competing market-maker that is affiliated with the clearing member (was incorrectly identified in the FIX spec as 'Competing dealer trades')",
"P": "Principal",
"R": "Transactions for the account of a non-member compting market-maker (was incorrectly identified in the FIX spec as 'Competing dealer trades')",
"S": "Specialist trades",
"T": "Transactions for the account of an unaffiliated member's competing market-maker (was incorrectly identified in the FIX spec as 'Competing dealer trades')",
"U": "Program Order, index arb, for other agency",
"W": "All other orders as agent for other member",
"X": "Short exempt transaction for member competing market-maker not affiliated with the firm clearing the trade (refer to W and T types)",
"Y": "Program Order, non-index arb, for other agency",
"Z": "Short exempt transaction for non-member competing market-maker (refer to A and R types)"
},
"54": {
"1": "Buy",
"2": "Sell",
"3": "Buy minus",
"4": "Sell plus",
"5": "Sell short",
"6": "Sell short exempt",
"7": "Undisclosed (valid for IOI and List Order messages only)",
"8": "Cross (orders where counterparty is an exchange, valid for all messages except IOIs)",
"9": "Cross short",
"A": "Cross short exempt",
"B": "'As Defined' (for use with multileg instruments)",
"C": "'Opposite' (for use with multileg instruments)",
"D": "Subscribe (e.g. CIV)",
"E": "Redeem (e.g. CIV)",
"F": "Lend (FINANCING - identifies direction of collateral)",
"G": "Borrow (FINANCING - identifies direction of collateral)"
},
"59": {
"0": "Day (or session)",
"1": "Good Till Cancel (GTC)",
"2": "At the Opening (OPG)",
"3": "Immediate Or Cancel (IOC)",
"4": "Fill Or Kill (FOK)",
"5": "Good Till Crossing (GTX)",
"6": "Good Till Date (GTD)",
"7": "At the Close"
},
"61": {
"0": "Normal",
"1": "Flash",
"2": "Background"
},
"63": {
"0": "Regular / FX Spot settlement (T+1 or T+2 depending on currency)",
"1": "Cash (TOD / T+0)",
"2": "Next Day (TOM / T+1)",
"3": "T+2",
"4": "T+3",
"5": "T+4",
"6": "Future",
"7": "When And If Issued",
"8": "Sellers Option",
"9": "T+5",
"B": "Broken date - for FX expressing non-standard tenor, SettlDate (64) must be specified",
"C": "FX Spot Next settlement (Spot+1, aka next day)"
},
"65": {
"CD": "EUCP with lump-sum interest rather than discount price",
"WI": "'When Issued' for a security to be reissued under an old CUSIP or ISIN"
},
"71": {
"0": "New",
"1": "Replace",
"2": "Cancel",
"3": "Preliminary (without MiscFees and NetMoney) (Removed/Replaced)",
"4": "Calculated (includes MiscFees and NetMoney) (Removed/Replaced)",
"5": "Calculated without Preliminary (sent unsolicited by broker, includes MiscFees and NetMoney) (Removed/Replaced)",
"6": "Reversal"
},
"77": {
"C": "Close",
                )RAW_DELIM";
                ss << R"RAW_DELIM(
"F": "FIFO",
"O": "Open",
"R": "Rolled"
},
"81": {
"0": "Regular",
"1": "Soft Dollar",
"2": "Step-In",
"3": "Step-Out",
"4": "Soft-dollar Step-In",
"5": "Soft-dollar Step-Out",
"6": "Plan Sponsor"
},
"87": {
"0": "accepted (successfully processed)",
"1": "block level reject",
"2": "account level reject",
"3": "received (received, not yet processed)",
"4": "incomplete",
"5": "rejected by intermediary",
"6": "allocation pending",
"7": "reversed"
},
"88": {
"0": "Unknown account(s)",
"1": "Incorrect quantity",
"10": "Unknown or stale ExecID",
"11": "Mismatched data",
"12": "Unknown ClOrdID",
"13": "Warehouse request rejected",
"2": "Incorrect averageg price",
"3": "Unknown executing broker mnemonic",
"4": "Commission difference",
"5": "Unknown OrderID (37)",
"6": "Unknown ListID (66)",
"7": "Other (further in Text (58))",
"8": "Incorrect allocated quantity",
"9": "Calculation difference"
},
"94": {
"0": "New",
"1": "Reply",
"2": "Admin Reply"
},
"97": {
"N": "Original Transmission",
"Y": "Possible Resend"
},
"98": {
"0": "None / Other",
"1": "PKCS (Proprietary)",
"2": "DES (ECB Mode)",
"3": "PKCS / DES (Proprietary)",
"4": "PGP / DES (Defunct)",
"5": "PGP / DES-MD5 (See app note on FIX web site)",
"6": "PEM / DES-MD5 (see app note on FIX web site)"
},
"102": {
"0": "Too late to cancel",
"1": "Unknown order",
"18": "Invalid price increment",
"2": "Broker / Exchange Option",
"3": "Order already in Pending Cancel or Pending Replace status",
"4": "Unable to process Order Mass Cancel Request",
"5": "OrigOrdModTime (586) did not match last TransactTime (60) of order",
"6": "Duplicate ClOrdID (11) received",
"99": "Other"
},
"103": {
"0": "Broker / Exchange option",
"1": "Unknown symbol",
"10": "Invalid Investor ID",
"11": "Unsupported order characteristic",
"12": "Surveillence Option",
"13": "Incorrect quantity",
"14": "Incorrect allocated quantity",
"15": "Unknown account(s)",
"18": "Invalid price increment",
"2": "Exchange closed",
"3": "Order exceeds limit",
"4": "Too late to enter",
"5": "Unknown order",
"6": "Duplicate Order (e.g. dupe ClOrdID)",
"7": "Duplicate of a verbally communicated order",
"8": "Stale order",
"9": "Trade along required",
"99": "Other"
},
"104": {
"A": "All or None (AON)",
"B": "Market On Close (MOC) (held to close)",
"C": "At the close (around/not held to close)",
"D": "VWAP (Volume Weighted Average Price)",
"I": "In touch with",
"L": "Limit",
"M": "More Behind",
"O": "At the Open",
"P": "Taking a Position",
"Q": "At the Market (previously called Current Quote)",
"R": "Ready to Trade",
"S": "Portfolio Shown",
"T": "Through the Day",
"V": "Versus",
"W": "Indidcation - Working Away",
"X": "Crossing Opportunity",
"Y": "At the Midpoint",
"Z": "Pre-open"
},
"113": {
"N": "Indicates the party sending message will report trade",
"Y": "Indicates the party receiving message must report trade"
},
"114": {
"N": "Indicates the broker is not required to locate",
"Y": "Indicates the broker is responsible for locating the stock"
},
"121": {
"N": "Do Not Execute Forex After Security Trade",
"Y": "Execute Forex After Security Trade"
},
"123": {
"N": "Sequence Reset, Ignore Msg Seq Num (N/A For FIXML - Not Used)",
"Y": "Gap Fill Message, Msg Seq Num Field Valid"
},
"127": {
"A": "Unknown Symbol",
"B": "Wrong Side",
"C": "Quantity Exceeds Order",
"D": "No Matching Order",
"E": "Price Exceeds Limit",
"F": "Calculation Difference",
"Z": "Other"
},
"130": {
"N": "Not Natural",
"Y": "Natural"
},
"139": {
"1": "Regulatory (e.g. SEC)",
"10": "Per transaction",
"11": "Conversion",
"12": "Agent",
"13": "Transfer Fee",
"14": "Security Lending",
"2": "Tax",
"3": "Local Commission",
"4": "Exchange Fees",
"5": "Stamp",
"6": "Levy",
"7": "Other",
"8": "Markup",
"9": "Consumption Tax"
},
"141": {
"N": "No",
"Y": "Yes, reset sequence numbers"
},
"150": {
"0": "New",
"3": "Done for day",
"4": "Canceled",
"5": "Replaced",
"6": "Pending Cancel (e.g. result of Order Cancel Request <F>)",
"7": "Stopped",
"8": "Rejected",
"9": "Suspended",
"A": "Pending New",
"B": "Calculated",
"C": "Expired",
"D": "Restated (Execution Report <8> sent unsolicited by sellside, with ExecRestatementReason <378> set)",
"E": "Pending Replace (e.g. result of Order Cancel/Replace Request <G>)",
"F": "Trade (partial fill or fill)",
"G": "Trade Correct",
"H": "Trade Cancel",
"I": "Order Status",
"J": "Trade in a Clearing Hold",
"K": "Trade has been released to Clearing",
"L": "Triggered or Activated by System"
},
"156": {
"D": "Divide",
"M": "Multiply"
},
"160": {
"0": "Default (Replaced)",
"1": "Standing Instructions Provided",
"2": "Specific Allocation Account Overriding (Replaced)",
"3": "Specific Allocation Account Standing (Replaced)",
"4": "Specific Order for a single account (for CIV)",
"5": "Request reject"
},
"163": {
"C": "Cancel",
"N": "New",
"R": "Replace",
"T": "Restate"
},
"165": {
"1": "Broker's Instructions",
"2": "Institution's Instructions",
"3": "Investor (e.g. CIV use)"
},
"166": {
"CED": "CEDEL",
"DTC": "Depository Trust Company",
"EUR": "Euro clear",
"FED": "Federal Book Entry",
"ISO_Country_Code": "Local Market Settle Location",
"PNY": "Physical",
"PTC": "Participant Trust Company"
},
"167": {
"ABS": "Asset-backed Securities",
"AMENDED": "Amended &amp; Restated",
"AN": "Other Anticipation Notes (BAN, GAN, etc.)",
"BA": "Bankers Acceptance",
"BN": "Bank Notes",
"BOX": "Bill Of Exchanges",
"BRADY": "Brady Bond",
"BRIDGE": "Bridge Loan",
"BUYSELL": "Buy Sellback",
"CASH": "Cash",
"CB": "Convertible Bond",
"CD": "Certificate Of Deposit",
"CL": "Call Loans",
"CMBS": "Corp. Mortgage-backed Securities",
"CMO": "Collateralized Mortgage Obligation",
"COFO": "Certificate Of Obligation",
"COFP": "Certificate Of Participation",
"CORP": "Corporate Bond",
"CP": "Commercial Paper",
"CPP": "Corporate Private Placement",
"CS": "Common Stock",
"DEFLTED": "Defaulted",
"DINP": "Debtor In Possession",
"DN": "Deposit Notes",
"DUAL": "Dual Currency",
"EUCD": "Euro Certificate Of Deposit",
"EUCORP": "Euro Corporate Bond",
"EUCP": "Euro Commercial Paper",
"EUSOV": "Euro Sovereigns *",
"EUSUPRA": "Euro Supranational Coupons *",
"FAC": "Federal Agency Coupon",
"FADN": "Federal Agency Discount Note",
"FOR": "Foreign Exchange Contract",
"FORWARD": "Forward",
"FUT": "Future",
"GO": "General Obligation Bonds",
"IET": "IOETTE Mortgage",
"LOFC": "Letter Of Credit",
"LQN": "Liquidity Note",
"MATURED": "Matured",
"MBS": "Mortgage-backed Securities",
"MF": "Mutual Fund",
"MIO": "Mortgage Interest Only",
"MLEG": "Multileg Instrument",
"MPO": "Mortgage Principal Only",
"MPP": "Mortgage Private Placement",
"MPT": "Miscellaneous Pass-through",
"MT": "Mandatory Tender",
"MTN": "Medium Term Notes",
"NONE": "No Security Type",
"ONITE": "Overnight",
"OOF": "Options on Futures",
"OOP": "Options on Physical",
"OPT": "Option",
"PEF": "Private Export Funding *",
"PFAND": "Pfandbriefe *",
"PN": "Promissory Note",
"PS": "Preferred Stock",
"PZFJ": "Plazos Fijos",
"RAN": "Revenue Anticipation Note",
"REPLACD": "Replaced",
"REPO": "Repurchase",
"RETIRED": "Retired",
"REV": "Revenue Bonds",
"RVLV": "Revolver Loan",
"RVLVTRM": "Revolver/Term Loan",
"SECLOAN": "Securities Loan",
"SECPLEDGE": "Securities Pledge",
"SPCLA": "Special Assessment",
"SPCLO": "Special Obligation",
"SPCLT": "Special Tax",
"STN": "Short Term Loan Note",
"STRUCT": "Structured Notes",
"SUPRA": "USD Supranational Coupons *",
"SWING": "Swing Line Facility",
"TAN": "Tax Anticipation Note",
"TAXA": "Tax Allocation",
"TBA": "To Be Announced",
"TBILL": "US Treasury Bill",
"TBOND": "US Treasury Bond",
"TCAL": "Principal Strip Of A Callable Bond Or Note",
"TD": "Time Deposit",
"TECP": "Tax Exempt Commercial Paper",
"TERM": "Term Loan",
"TINT": "Interest Strip From Any Bond Or Note",
"TIPS": "Treasury Inflation Protected Securities",
"TNOTE": "US Treasury Note",
"TPRN": "Principal Strip From A Non-Callable Bond Or Note",
"TRAN": "Tax Revenue Anticipation Note",
"UST": "US Treasury Note (Deprecated Value Use TNOTE)",
"USTB": "US Treasury Bill (Deprecated Value Use TBILL)",
"VRDN": "Variable Rate Demand Note",
"WAR": "Warrant",
"WITHDRN": "Withdrawn",
"WLD": "Wildcard Entry (was '?' in 4.4, used on Security Definition Request message)",
"XCN": "Extended Comm Note",
"XLINKD": "Indexed Linked",
"YANK": "Yankee Corporate Bond",
"YCD": "Yankee Certificate Of Deposit"
},
"169": {
"0": "Other",
"1": "DTC SID",
"2": "Thomson ALERT",
"3": "A Global Custodian (StandInstDBName (70) must be provided)",
"4": "AccountNet"
},
"172": {
"0": "'Versus. Payment': Deliver (if Sell) or Receive (if Buy) vs. (Against) Payment",
"1": "'Free': Deliver (if Sell) or Receive (if Buy) Free",
"2": "Tri-Party",
"3": "Hold In Custody"
},
"197": {
"0": "FX Netting",
"1": "FX Swap"
},
"201": {
"0": "Put",
"1": "Call"
},
"203": {
"0": "Covered",
"1": "Uncovered"
},
"204": {
"0": "Customer",
"1": "Firm"
},
"208": {
"N": "Details shoult not be communicated",
"Y": "Details should be communicated"
},
"209": {
"1": "Match",
"2": "Forward",
"3": "Forward and Match"
},
"216": {
"1": "Target Firm",
"2": "Target List",
"3": "Block Firm",
"4": "Block List"
},
"219": {
"1": "CURVE",
"2": "5YR",
"3": "OLD5",
"4": "10YR",
"5": "OLD10",
"6": "30YR",
"7": "OLD30",
"8": "3MOLIBOR",
"9": "6MOLIBOR"
},
"221": {
"EONIA": "EONIA",
"EUREPO": "EUREPO",
"Euribor": "Euribor",
"FutureSWAP": "FutureSWAP",
"LIBID": "LIBID",
"LIBOR": "LIBOR (London Inter-Bank Offer)",
"MuniAAA": "MuniAAA",
"OTHER": "OTHER",
"Pfandbriefe": "Pfandbriefe",
"SONIA": "SONIA",
"SWAP": "SWAP",
"Treasury": "Treasury"
},
"233": {
"ABS": "Absolute Prepayment Speed",
"AMT": "Alternative Minimum Tax (Y/N)",
"AUTOREINV": "Auto Reinvestment at or better",
"BANKQUAL": "Bank qualified (Y/N)",
"BGNCON": "Bargain conditions (see StipulationValue (234) for values)",
"COUPON": "Coupon range",
"CPP": "Constant Prepayment Penalty",
"CPR": "Constant Prepayment Rate",
"CPY": "Constant Prepayment Yield",
"CURRENCY": "ISO Currency Code",
"CUSTOMDATE": "Custom start/end date",
"GEOG": "Geographics and % range (ex. 234=CA 0-80 [minimum of 80% California assets])",
"HAIRCUT": "Valuation Discount",
"HEP": "final CPR of Home Equity Prepayment Curve",
"INSURED": "Insured (Y/N)",
"ISSUE": "Year Or Year/Month of Issue (ex. 234=2002/09)",
"ISSUER": "Issuer's ticker",
"ISSUESIZE": "issue size range",
"LOOKBACK": "Lookback Days",
"LOT": "Explicit lot identifier",
"LOTVAR": "Lot Variance (value in percent maximum over- or under-allocation allowed)",
"MAT": "Maturity Year And Month",
"MATURITY": "Maturity range",
"MAXSUBS": "Maximum substitutions (Repo)",
"MHP": "Percent of Manufactured Housing Prepayment Curve",
"MINDNOM": "Minimum denomination",
"MININCR": "Minimum increment",
"MINQTY": "Minimum quantity",
"MPR": "Monthly Prepayment Rate",
"PAYFREQ": "Payment frequency, calendar",
"PIECES": "Number Of Pieces",
"PMAX": "Pools Maximum",
"PPC": "Percent of Prospectus Prepayment Curve",
"PPL": "Pools per Lot",
"PPM": "Pools per Million",
"PPT": "Pools per Trade",
"PRICE": "Price Range",
"PRICEFREQ": "Pricing frequency",
"PROD": "Production Year",
"PROTECT": "Call protection",
"PSA": "Percent of BMA Prepayment Curve",
"PURPOSE": "Purpose",
"PXSOURCE": "Benchmark price source",
"RATING": "Rating source and range",
"REDEMPTION": "Type Of Redemption - values are: NonCallable, Prefunded, EscrowedToMaturity, Putable, Convertible",
"RESTRICTED": "Restricted (Y/N)",
"SECTOR": "Market Sector",
"SECTYPE": "Security Type included or excluded",
"SMM": "Single Monthly Mortality",
"STRUCT": "Structure",
"SUBSFREQ": "Substitutions frequency (Repo)",
"SUBSLEFT": "Substitutions left (Repo)",
"TEXT": "Freeform Text",
"TRDVAR": "Trade Variance (value in percent maximum over- or under-allocation allowed)",
"WAC": "Weighted Average Coupon - value in percent (exact or range) plus 'Gross' or 'Net' of servicing spread (the default) (ex. 234=6.5-Net [minimum of 6.5% net of servicing fee])",
"WAL": "Weighted Average Life Coupon - value in percent (exact or range)",
"WALA": "Weighted Average Loan Age - value in months (exact or range)",
"WAM": "Weighted Average Maturity - value in months (exact or range)",
"WHOLE": "Whole Pool (Y/N)",
"YIELD": "Yield Range"
},
"235": {
"AFTERTAX": "After Tax Yield (Municipals)",
"ANNUAL": "Annual Yield",
"ATISSUE": "Yield At Issue (Municipals)",
"AVGMATURITY": "Yield To Avg Maturity",
"BOOK": "Book Yield",
"CALL": "Yield to Next Call",
"CHANGE": "Yield Change Since Close",
"CLOSE": "Closing Yield",
"COMPOUND": "Compound Yield",
"CURRENT": "Current Yield",
"GOVTEQUIV": "Gvnt Equivalent Yield",
"GROSS": "True Gross Yield",
"INFLATION": "Yield with Inflation Assumption",
"INVERSEFLOATER": "Inverse Floater Bond Yield",
"LASTCLOSE": "Most Recent Closing Yield",
"LASTMONTH": "Closing Yield Most Recent Month",
"LASTQUARTER": "Closing Yield Most Recent Quarter",
"LASTYEAR": "Closing Yield Most Recent Year",
"LONGAVGLIFE": "Yield to Longest Average Life",
"MARK": "Mark to Market Yield",
"MATURITY": "Yield to Maturity",
"NEXTREFUND": "Yield to Next Refund (Sinking Fund Bonds)",
"OPENAVG": "Open Average Yield",
"PREVCLOSE": "Previous Close Yield",
"PROCEEDS": "Proceeds Yield",
"PUT": "Yield to Next Put",
"SEMIANNUAL": "Semi-annual Yield",
"SHORTAVGLIFE": "Yield to Shortest Average Life",
"SIMPLE": "Simple Yield",
"TAXEQUIV": "Tax Equivalent Yield",
"TENDER": "Yield to Tender Date",
"TRUE": "True Yield",
"VALUE1_32": "Yield Value Of 1/32",
"WORST": "Yield To Worst"
},
"258": {
"N": "Not Traded Flat",
"Y": "Traded Flat"
},
"263": {
"0": "Snapshot",
"1": "Snapshot + Updates (Subscribe)",
"2": "Disable previous Snapshot + Update Request (Unsubscribe)"
},
"264": {
"0": "Full Book depth",
"1": "Top of Book",
"2": "Book Depth (number of levels)"
},
"265": {
"0": "Full refresh",
"1": "Incremental refresh"
},
"266": {
"N": "book entries should not be aggregated",
"Y": "book entries to be aggregated"
                )RAW_DELIM";
                ss << R"RAW_DELIM(
},
"269": {
"0": "Bid",
"1": "Offer",
"2": "Trade",
"3": "Index Value",
"4": "Opening Price",
"5": "Closing Price",
"6": "Settlement Price",
"7": "Trading Session High Price",
"8": "Trading Session Low Price",
"9": "Trading Session VWAP Price",
"A": "Imbalance",
"B": "Trade Volume",
"C": "Open Interest",
"D": "Composite Underlying Price",
"E": "Simulated Sell Price",
"F": "Simulated Buy Price",
"G": "Margin Rate",
"H": "Mid Price",
"J": "Empty Book",
"K": "Settle High Price",
"L": "Settle Low Price",
"M": "Prior Settle Price",
"N": "Session High Bid",
"O": "Session Low Offer",
"P": "Early Prices",
"Q": "Auction Clearing Price"
},
"274": {
"0": "Plus Tick",
"1": "Zero-Plus Tick",
"2": "Minus Tick",
"3": "Zero-Minus Tick"
},
"276": {
"0": "Reserved SAM",
"1": "No Active SAM",
"2": "Restricted",
"A": "Open/Active",
"B": "Closed/Inactive",
"C": "Exchange Best",
"D": "Consolidated Best",
"E": "Locked",
"F": "Crossed",
"G": "Depth",
"H": "Fast Trading",
"I": "Non-Firm",
"J": "Outright Price",
"K": "Implied Price",
"L": "Manual/Slow Quote",
"M": "Depth on Offer",
"N": "Depth on Bid",
"O": "Closing",
"P": "News Dissemination",
"Q": "Trading Range",
"R": "Order Influx",
"S": "Due to Related",
"T": "News Pending",
"U": "Additional Info",
"V": "Additional Info due to related",
"W": "Resume",
"X": "View of Common",
"Y": "Volume Alert",
"Z": "Order Imbalance",
"a": "Equipment Changeover",
"b": "No Open / No Resume",
"c": "Regular ETH",
"d": "Automatic Execution",
"e": "Automatic Execution ETH",
"f": "Fast Market ETH",
"g": "Inactive ETH",
"h": "Rotation",
"i": "Rotation ETH",
"j": "Halt",
"k": "Halt ETH",
"l": "Due to News Dissemination",
"m": "Due to News Pending",
"n": "Trading Resume",
"o": "Out of Sequence",
"p": "Bid Specialist",
"q": "Offer Specialist",
"r": "Bid Offer Specialist",
"s": "End of Day SAM",
"t": "Forbidden SAM",
"u": "Frozen SAM",
"v": "PreOpening SAM",
"w": "Opening SAM",
"x": "Open SAM",
"y": "Surveillance SAM",
"z": "Suspended SAM"
},
"277": {
"0": "Cancel",
"A": "Cash (only) Market",
"AA": "Spread",
"AB": "Spread ETH",
"AC": "Straddle",
"AD": "Straddle ETH",
"AE": "Stopped",
"AF": "Stopped ETH",
"AG": "Regular ETH",
"AH": "Combo",
"AI": "Combo ETH",
"AJ": "Official Closing Price",
"AK": "Prior Reference Price",
"AL": "Stopped Sold Last",
"AM": "Stopped Out of Sequence",
"AN": "Offical Closing Price",
"AO": "Crossed Trade",
"AP": "Fast Market",
"AQ": "Automatic Execution",
"AR": "Form T",
"AS": "Basket Index",
"AT": "Burst Basket",
"B": "Average Price Trade",
"C": "Cash Trade (same day clearing)",
"D": "Next Day (only)Market",
"E": "Opening/Reopening Trade Detail",
"F": "Intraday Trade Detail",
"G": "Rule 127 Trade (NYSE)",
"H": "Rule 155 Trade (AMEX)",
"I": "Sold Last (late reporting)",
"J": "Next Day Trade (next day clearing)",
"K": "Opened (late report of opened trade)",
"L": "Seller",
"M": "Sold (out of sequence)",
"N": "Stopped Stock (guarantee of price but does not execute the order)",
"P": "Imbalance More Buyers (cannot be used in combination with Q)",
"Q": "Imbalance More Sellers (cannot be used in combination with P)",
"R": "Opening Price",
"S": "Bargain Condition (LSE)",
"T": "Converted Price Indicator",
"U": "Exchange Last",
"V": "Final Price of Session",
"W": "Ex-pit",
"X": "Crossed",
"Y": "Trades resulting from manual/slow quote",
"Z": "Trades resulting from intermarket sweep",
"a": "Volume Only",
"b": "Direct Plus",
"c": "Acquisition",
"d": "Bunched",
"e": "Distribution",
"f": "Bunched Sale",
"g": "Split Trade",
"h": "Cancel Stopped",
"i": "Cancel ETH",
"j": "Cancel Stopped ETH",
"k": "Out of Sequence ETH",
"l": "Cancel Last ETH",
"m": "Sold Last Sale ETH",
"n": "Cancel Last",
"o": "Sold Last Sale",
"p": "Cancel Open",
"q": "Cancel Open ETH",
"r": "Opened Sale ETH",
"s": "Cancel Only",
"t": "Cancel Only ETH",
"u": "Late Open ETH",
"v": "Auto Execution ETH",
"w": "Reopen",
"x": "Reopen ETH",
"y": "Adjusted",
"z": "Adjusted ETH"
},
"279": {
"0": "New",
"1": "Change",
"2": "Delete",
"3": "Delete Thru",
"4": "Delete From"
},
"281": {
"0": "Unknown symbol",
"1": "Duplicate MDReqID",
"2": "Insufficient Bandwidth",
"3": "Insufficient Permissions",
"4": "Unsupported SubscriptionRequestType",
"5": "Unsupported MarketDepth",
"6": "Unsupported MDUpdateType",
"7": "Unsupported AggregatedBook",
"8": "Unsupported MDEntryType",
"9": "Unsupported TradingSessionID",
"A": "Unsupported Scope",
"B": "Unsupported OpenCloseSettleFlag",
"C": "Unsupported MDImplicitDelete",
"D": "Insufficient credit"
},
"285": {
"0": "Cancellation / Trade Bust",
"1": "Error"
},
"286": {
"0": "Daily Open / Close / Settlement entry",
"1": "Session Open / Close / Settlement entry",
"2": "Delivery Settlement entry",
"3": "Expected entry",
"4": "Entry from previous business day",
"5": "Theoretical Price value"
},
"291": {
"1": "Bankrupt",
"2": "Pending delisting",
"3": "Restricted"
},
"292": {
"A": "Ex-Dividend",
"B": "Ex-Distribution",
"C": "Ex-Rights",
"D": "New",
"E": "Ex-Interest",
"F": "Cash Dividend",
"G": "Stock Dividend",
"H": "Non-Integer Stock Split",
"I": "Reverse Stock Split",
"J": "Standard-Integer Stock Split",
"K": "Position Consolidation",
"L": "Liquidation Reorganization",
"M": "Merger Reorganization",
"N": "Rights Offering",
"O": "Shareholder Meeting",
"P": "Spinoff",
"Q": "Tender Offer",
"R": "Warrant",
"S": "Special Action",
"T": "Symbol Conversion",
"U": "CUSIP / Name Change",
"V": "Leap Rollover"
},
"297": {
"0": "Accepted",
"1": "Cancel for Symbol(s)",
"10": "Pending",
"11": "Pass",
"12": "Locked Market Warning",
"13": "Cross Market Warning",
"14": "Canceled Due To Lock Market",
"15": "Canceled Due To Cross Market",
"2": "Canceled for Security Type(s)",
"3": "Canceled for Underlying",
"4": "Canceled All",
"5": "Rejected",
"6": "Removed from Market",
"7": "Expired",
"8": "Query",
"9": "Quote Not Found"
},
"298": {
"1": "Cancel for Symbol(s)",
"2": "Cancel for Security Type(s)",
"3": "Cancel for Underlying Symbol",
"4": "Cancel All Quotes",
"5": "Cancel quote specified in QuoteID"
},
"300": {
"1": "Unknown Symbol (security)",
"2": "Exchange (Security) closed",
"3": "Quote <S> exceeds limit",
"4": "Too late to enter",
"5": "Unknown Quote <S>",
"6": "Duplicate Quote <S>",
"7": "Invalid bid/ask spread",
"8": "Invalid price",
"9": "Not authorized to quote security",
"99": "Other"
},
"301": {
"0": "No Acknowledgement (default)",
"1": "Acknowledge only negative or erroneous quotes",
"2": "Acknowledge each quote messages"
},
"303": {
"1": "Manual",
"2": "Automatic"
},
"321": {
"0": "Request Security identity and specifications",
"1": "Request Security identity for the specifications provided (name of the security is not supplied)",
"2": "Request List Security Types",
"3": "Request List Securities (can be qualified with Symbol, SecurityType, TradingSessionID, SecurityExchange. If provided then only list Securities for the specific type.)"
},
"323": {
"1": "Accept security proposal as-is",
"2": "Accept security proposal with revisions as indicated in the message",
"3": "List of security types returned per request",
"4": "List of securities returned per request",
"5": "Reject security proposal",
"6": "Cannot match selection criteria"
},
"325": {
"N": "Message is being sent as a result of a prior request",
"Y": "Message is being secnt unsolicited"
},
"326": {
"1": "Opening delay",
"10": "Market on Close Imbalance Sell",
"11": "(not assigned)",
"12": "No Market Imbalance",
"13": "No Market on Close Imbalance",
"14": "ITS Pre-opening",
"15": "New Price Indication",
"16": "Trade Dissemination Time",
"17": "Ready to trade (start of session)",
"18": "Not available for trading (end of session)",
"19": "Not traded on this market",
"2": "Trading halt",
"20": "Unknown or Invalid",
"21": "Pre-open",
"22": "Opening Rotation",
"23": "Fast Market",
"3": "Resume",
"4": "No Open / No Resume",
"5": "Price indication",
"6": "Trading Range Indication",
"7": "Market Imbalance Buy",
"8": "Market Imbalance Sell",
"9": "Market on Close Imbalance Buy"
},
"327": {
"D": "News Dissemination",
"E": "Order Influx",
"I": "Order Imbalance",
"M": "Additional Information",
"P": "New Pending",
"X": "Equipment Changeover"
}
}
}
                )RAW_DELIM";
            }

            return ss.str();
        }
    };
} // namespace rda
